containerbin:
	go get github.com/rjeczalik/pkgconfig/cmd/pkg-config
	go get -v github.com/mattn/go-oci8
	go get github.com/golang/protobuf/proto
	go get github.com/gorilla/mux
	go get github.com/xtracdev/goes
	go get github.com/xtracdev/oraeventstore
	go build -o appreg
